NTPasswd: 0fF307 | F4 | F5                          Выход: 0f<ESC>07

 0f"Прохождение" Offline NT Password and registry editor07

1. Запускаем нужный пункт меню. Дожидаемся сообщения вида:
0f
  =========================================================
  ¤ Step ONE: Select disk where the Windows installation is
  =========================================================
07

2. Выбираем по номеру раздел с целевой системой. Обычно это 1 (на ноутбуках - 2). Используйте здравый смысл. Видим:
0f
  =========================================================
  ¤ Step TWO: Select PATH and registry files
  =========================================================
  What is the path to the registry directory? (relative to windows disk)
  [WINDOWS/system32/config] :
07
Нажимаем Enter.
0f
  Select which part of registry to load, use predefined choices
  or list the files with space as delimiter
07
Нажимаем 1.

