NTPasswd: F3 | F4 | 0fF507                          Выход: 0f<ESC>07
0f
  - - - - User Edit Menu:
   1 - Clear (blank) user password
   2 - Edit (set new) user password (careful with this on XP or Vista)
   3 - Promote user (make user an administrator)
  (4 - Unlock and enable user account) [seems unlocked already]
   q - Quit editing user, back to user select
07
1 - очистить пароль (лучше очистить, чем изменить), 2 - изменить, 3 - дать права администратора, 4 - разблокировать (в приведённом примере уже разблокирован), q - закончить изменения.
Выбираем нужный пункт, потом последовательно выбираем пункты, отвечающие за выход из программы: q, !, q.
0f
  =========================================================
  ¤ Step FOUR: Writing back changes
  =========================================================
  About to write file(s) back! Do it? [n] :
07
Вводим y.
0f
  ***** EDIT COMPLETE *****

  You can try again if it somehow failed, or you selected wrong
  New run? [n] :
07
Вводим n, нажимаем Ctrl+Alt+Delete, пользуемся.
